services:
  tests:
    build:
      context: .
      target: tdd
    user: "${DOCKER_BUILD_UID:-1000}:${DOCKER_BUILD_GID:-1000}"
    environment:
      JDK_JAVA_OPTIONS: -XX:UseSVE=0
      JAVA_TOOL_OPTIONS: -XX:UseSVE=0
    volumes:
      - ./src/:/home/jdk_user/src/:delegated
